arch: amd64

language: java

jdk: 
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

script:
  - java --version
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V
  - ./mvnw clean install
  - ./mvnw test